config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/main')

  get '/auth/:provider/callback' => 'user_sessions#create'
  resource :user_session, only: %w[ new destroy ]

  namespace :api do
    resources :things, only: %w[ index show create ] do
      resource :score, only: %w[ show update ]
      resources :comments, only: %w[ index show create ]
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get '/main/(*path)' => 'main#index', as: :main

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Thing, approved: true
    can :create, Thing

    can :read, Comment
    can :create, Comment do |comment|
      can? :read, Thing
    end

    if user
      can :manage, Score, user_id: user.id
    end
  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin   # grant access to rails_admin
      can :dashboard              # grant access to the dashboard

      can :manage, Thing
      can :manage, Tag
      can :manage, User
      can :manage, Score
      cannot :destroy, User
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing

  validates :message, presence: true
  validates :user, presence: true
  validates :thing, presence: true

  delegate :name, to: :user, prefix: true
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :thing
  belongs_to :user

  validates :thing, presence: true
  validates :user, presence: true
  validates :value, presence: true, inclusion: { in: [ -1, 1 ] }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :value, presence: true, uniqueness: { case_sensitive: false }

  has_many :tag_of_things, dependent: :destroy
  has_many :things, through: :tag_of_things

  def self.recommendations_for(user)
    self.joins(:things => :scores).where(scores: { user_id: user }).
      group('tags.id').having('sum(scores.value) >= 0 AND count(scores.id) > 0')
  end
end

app/models/tag_of_thing.rb
class TagOfThing < ActiveRecord::Base
  belongs_to :tag
  belongs_to :thing

  validates :tag, presence: true
  validates :thing, presence: true

  validates :tag_id, uniqueness: { scope: :thing_id }
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :tag_of_things, dependent: :destroy
  has_many :tags, through: :tag_of_things
  has_many :scores, dependent: :destroy
  has_many :users, through: :scores
  has_many :comments, dependent: :destroy

  def self.unchecked_for(user)
    self.where.not(id: user.things.select('things.id'))
  end

  def self.checked_for(user)
    self.where(id: user.things.select('things.id'))
  end

  def self.recommendations_for(user)
    tag_ids = Tag.recommendations_for(user).select('tags.id')
    self.unchecked_for(user).joins(:tags).where(tags: { id: tag_ids}).uniq
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true

  has_many :scores, dependent: :destroy
  has_many :things, through: :scores
  has_many :comments, dependent: :destroy
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  include Roar::Rails::ControllerAdditions

  respond_to :json

end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::BaseController

  load_and_authorize_resource :thing
  load_and_authorize_resource :comment, through: :thing

  after_action :trigger_new_comment, only: :create

  def index
    @comments.preload!(:user)
    respond_with @comments
  end

  def show
    respond_with @comment
  end

  def create
    @comment = @thing.comments.create(comment_params) do |comment|
      comment.user = current_user
    end
    respond_with @comment, location: [ :api, @thing, @comment ]
  end

protected

  def comment_params
    params.require(:comment).permit(:message)
  end

  def trigger_new_comment
    if @comment.persisted?
      comment_hash = @comment.dup.extend(::Api::CommentRepresenter).to_hash
      WebsocketRails["things/#{@thing.id}/comments"].trigger :new, comment_hash
    end
  end

end

app/controllers/api/scores_controller.rb
class Api::ScoresController < Api::BaseController

  load_and_authorize_resource :thing

  before_action :load_score

  def show
    respond_with @score
  end

  def update
    @score.update_attributes(score_params)
    respond_with @score
  end

protected

  def score_params
    params[:score].permit(:value)
  end

  def load_score
    @score = @thing.scores.find_or_initialize_by(user: current_user)
  end

end

app/controllers/api/things_controller.rb
class Api::ThingsController < Api::BaseController
  load_and_authorize_resource

  def index
    @things = @things.recommendations_for(current_user) if params[:recommendations]
    @things = @things.unchecked_for(current_user) if params[:unchecked]
    @things = @things.checked_for(current_user) if params[:checked]
    @things.preload!(:tags)
    respond_with @things
  end

  def show
    respond_with @thing
  end

  def create
    @thing = Thing.create(thing_params)
    respond_with @thing, location: [ :api, @thing ]
  end

protected

  def thing_params
    params.require(:thing).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to main_app.root_path, alert: exception.message }
      format.json { head status: :forbidden }
    end
  end

protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session.key?(:user_id)
  end

  def require_user!
    unless current_user
      respond_to do |format|
        format.html { redirect_to new_user_session_path }
        format.any { head :forbidden  }
      end
    end
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :require_user!

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  respond_to :html

  def new
  end

  def create
    user = User.create_with(name: auth_hash.info.name).find_or_create_by!(facebook_id: auth_hash.uid)
    if user.persisted?
      session[:user_id] = user.id 
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to new_user_session_path
  end

protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper

  def auth_path(provider)
    "/auth/#{provider}"
  end

end

app/views/layouts/application.html.slim
doctype html
html ng-app=@ngApp
  head
    title Recommendations
    script= render 'shared/twitter_wjs.js'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application', media: 'all'
    = csrf_meta_tags
    = yield :head if content_for?(:head)
  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to t('.home'), root_path, class: 'navbar-brand'
          a.navbar-toggle data-toggle="collapse" href="#navbar-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar

        #navbar-collapse.collapse.navbar-collapse
          ul.nav.navbar-nav
            = yield :navbar if content_for?(:navbar)
          ul.nav.navbar-nav.navbar-right
            = yield :navbar_right if content_for?(:navbar_right)
            - if current_user
              li.dropdown
                a.dropdown-toggle.btn.btn-link data-toggle="dropdown"
                  = current_user.name
                  b.caret
                ul.dropdown-menu
                  - if current_user.admin?
                    li = link_to t('.amdin_panel'), rails_admin_path, target: '_self'
                  li = link_to t('.sign_out'), user_session_path, method: :delete
            - else
              li = link_to t('.sign_in'), new_user_session_path
    .container= yield

app/views/main/index.html.slim
- @ngApp ="RecommendationsApplication"

= content_for :head do
  = stylesheet_link_tag 'main/application', media: 'all'
  = javascript_include_tag 'main/application'

  meta name="fragment" content="!"
  base href=main_path

= content_for :navbar do
  li: a href=main_path("things") translate="things.index.title"
  li: a href=main_path("things/recommended") translate="things.recommended.title"
  li: a href=main_path("things/unchecked") translate="things.unchecked.title"
  li: a href=main_path("things/checked") translate="things.checked.title"
  li: a href=main_path("things/new") translate="things.new.title"

- content_for :navbar_right do
  li.dropdown ng-controller="TranslationController"
    a.dropdown-toggle.btn.btn-link data-toggle="dropdown"
      | {{currentLocale}}
      b.caret
    ul.dropdown-menu
      - I18n.available_locales.each do |locale|
        li: a ng-click="setLocale('#{locale}')" = locale

div ng-view=true

app/views/user_sessions/new.html.slim
.text-center
  h1 = t('.sign_in')

  = link_to t('.via_facebook'), auth_path(:facebook), class: 'btn btn-primary btn-lg'